(function(){
  'use strict';
  function tach(text){var clean=text.replace(/(^|[^\\])%[^\r\n]*/gm,function(all,prefix){return prefix+' '.repeat(all.length-prefix.length);});var matches=Array.from(clean.matchAll(/\\begin\{tikzpicture\}[\s\S]*?\\end\{tikzpicture\}/g));if(matches.length!==1)throw Error(matches.length?'Mỗi mẫu chỉ nhận một hình. Hãy tách từng khối tikzpicture.':'Cần một khối begin{tikzpicture} đến end{tikzpicture}.');return text.slice(matches[0].index,matches[0].index+matches[0][0].length);}
  function chuan(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d');}
  function boc(source,macro){return '\\documentclass[tikz,border=3pt]{standalone}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T5]{fontenc}\n\\usepackage{amsmath,amssymb,amsfonts,mathrsfs}\n\\usepackage{tikz,tkz-euclide,pgfplots}\n\\usetikzlibrary{calc,angles,quotes,intersections,through,backgrounds,patterns,shapes.geometric,arrows.meta}\n\\pgfplotsset{compat=1.18}\n'+(macro||'')+'\n\\begin{document}\n'+source+'\n\\end{document}';}
  function ten(title,id){return (chuan(title).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,65)||'hinh')+'-'+id.slice(0,8);}
  // Rút gọn log biên dịch: giữ các dòng "! ..." và vài dòng ngữ cảnh (l.<số>) sau đó.
  function loiBuild(text){text=String(text||'');try{var j=JSON.parse(text);var g=[j.detail,j.error,j.message,j.log,j.stderr,j.stdout,j.output&&j.output.log].filter(function(x){return typeof x==='string'&&x;}).join('\n');if(g)text=g;}catch(e){}
    var d=text.split(/\r?\n/),ra=[];for(var i=0;i<d.length&&ra.length<6;i++){if(/^!/.test(d[i])){var k=i+1;while(k<d.length&&k<i+7&&!/^!/.test(d[k]))k++;ra.push(d.slice(i,k).join('\n'));i=k-1;}}
    if(!ra.length)d.forEach(function(l){if(ra.length<20&&/error|undefined|missing|runaway|not defined|unknown|emergency/i.test(l))ra.push(l);});
    return((ra.length?ra.join('\n...\n'):text.slice(-3000))||'Biên dịch thất bại nhưng dịch vụ không trả log.').slice(0,5000);}
  window.Tikz={loiBuild:loiBuild,tach:tach,chuan:chuan,boc:boc,ten:ten,moi:function(){return{id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2),title:'',kind:'real',grade:'',topic:'',tags:'',description:'',source:'\\begin{tikzpicture}\n  % Dán mã hình của bạn\n\\end{tikzpicture}',image:''};},tim:function(items,prompt){var words=Array.from(new Set(chuan(prompt).split(/[^a-z0-9]+/).filter(function(w){return w.length>1;})));return items.map(function(item){var s=chuan([item.title,item.topic,item.tags,item.description].join(' '));return{item:item,score:words.reduce(function(n,w){return n+(s.indexOf(w)>=0?1:0);},0)};}).filter(function(x){return x.score>0;}).sort(function(a,b){return b.score-a.score;}).slice(0,8).map(function(x){return x.item;});}};
})();
